config/routes.rb
Rails.application.routes.draw do
  get "/check_visitor", to: 'visitors#check_visitor', as: 'check_visitor'
  get "/about_us", to: 'home#about_us', as: 'about_us'
  resources :visitors
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  authenticated :user do
    root to: 'visitors#index', as: :authenticated_root
  end

  root to:'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/visitor.rb
class Visitor < ApplicationRecord
  after_create :send_mail_to_owner

  def send_mail_to_owner
    UserMailer.visitor_information(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path(resource)
    visitors_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about_us
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :set_visitor, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /visitors or /visitors.json
  def index
    @visitors = Visitor.all
    time = Time.now
    @today_visitors = @visitors.where(:last_visited => time.beginning_of_day..time.end_of_day)
    @weekly_visitors = @visitors.where(:last_visited => (time - 7.days).beginning_of_day..time.end_of_day)
  end

  # GET /visitors/1 or /visitors/1.json
  def show
  end

  # GET /visitors/new
  def new
    @visitor = Visitor.new
  end

  # GET /visitors/1/edit
  def edit
  end

  # POST /visitors or /visitors.json
  def create
    @visitor = Visitor.new(visitor_params)

    respond_to do |format|
      if @visitor.save
        format.html { redirect_to visitor_url(@visitor), notice: "Visitor was successfully created." }
        format.json { render :show, status: :created, location: @visitor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  def check_visitor
    access_key_id = ENV['ACCESS_KEY_ID']
    secret_access_key = ENV['SECRET_ACCESS_KEY']
    s3 = Aws::S3::Client.new(access_key_id: access_key_id, secret_access_key: secret_access_key)
    bucket = 'visitorsreco'
    s3.list_objects(bucket: bucket).each do |response|
      response.contents.each do |object|
        photo  = object.key
        client   = Aws::Rekognition::Client.new(region: 'ap-south-1', access_key_id: access_key_id, secret_access_key: secret_access_key)
        attrs = {image: { s3_object: { bucket: bucket, name: photo},}, attributes: ['ALL']}
        response = client.detect_faces attrs
        low  = 0
        high = 0
        gender = nil
        response.face_details.each do |face_detail|
          low  = face_detail.age_range.low
          high = face_detail.age_range.high
          gender = face_detail.gender.value
        end
        File.open(Rails.root.join("public/camera_images")+"#{object.key}", 'wb') do |file|
          reap = s3.get_object({ bucket:bucket, key: photo }, target: file)
          base_64_string = Base64.encode64(open(file) { |io| io.read })
          visitor = Visitor.find_or_create_by(image_string: base_64_string)
          classification = visitor.no_of_visit.nil? ? 'stranger' : visitor.classification
          visitor.update(no_of_visit: visitor.no_of_visit.to_i + 1, last_visited: Time.now, classification: classification, gender: gender)
          File.delete(file) if File.exist?(file)
          s3.delete_object({ bucket:bucket, key: photo })
        end
      end
    end
    redirect_to visitors_url
  end

  # PATCH/PUT /visitors/1 or /visitors/1.json
  def update
    respond_to do |format|
      if @visitor.update(visitor_params)
        format.html { redirect_to visitor_url(@visitor), notice: "Visitor was successfully updated." }
        format.json { render :show, status: :ok, location: @visitor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitors/1 or /visitors/1.json
  def destroy
    @visitor.destroy

    respond_to do |format|
      format.html { redirect_to visitors_url, notice: "Visitor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visitor
      @visitor = Visitor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def visitor_params
      params.require(:visitor).permit(:name, :relation, :classification, :no_of_visit, :last_visited, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/home/about_us.html.erb
<div class="container-fluid pt-3 mt-3 text-white" style='background-color: #3fa590;'>
  <div class="row">
    <div class="col-2"></div>
    <div class="col-8 text-center text-dark">
      <h1>My First Bootstrap Page</h1>
      <p style="font-size: 30px;">We are all very different. We were born in different cities, at different times, we love different music, food, movies. But we have something that unites us all. It is our company. We are its heart. We are not just a team, we are a family.</p>
    </div>
    <div class="col-2"></div>
  </div>
</div>

<div class="container-fluid pt-3 mt-3 text-white" style='background-color: #ffffff;'>
  <div class="row">
    <div class="col-2"></div>
    <div class="col-8 text-center text-dark">
      <div class="row">
        <div class="col-4">
          <%= image_tag("first.png", height: '150') %>
          <h4>Creativity</h4>
          <p>
            It's the ability to think outside the box. We make decisions, create something new and generate a lot of ideas.
          </p>
        </div>
        <div class="col-4">
          <%= image_tag("second.png", height: '150') %>
          <h4>Worldwide</h4>
          <p class="mbr-text mbr-fonts-style display-7">
            All sites you make with Mobirise are mobile-friendly. You don't have to create a special mobile version of your site.
          </p>
        </div>
        <div class="col-4">
          <%= image_tag("third.png", height: '150') %>
          <h4>Unique Styles</h4>
          <p class="mbr-text mbr-fonts-style display-7">
            Mobirise offers many site blocks in several themes, and though these blocks are pre-made, they are flexible.
          </p>
        </div>
      </div>
    </div>
    <div class="col-2"></div>
  </div>



</div>

app/views/home/index.html.erb
<div class="section1 d-flex flex-column bd-highlight text-white bg-gradient">
  <div class="p-2 bd-highlight"><p class="fs-1">There’s no place like home.</p></div>
  <div class="p-2 bd-highlight"><p class="fs-5">Smart home systems achieved great popularity in the last decades as they increase the comfort and quality of life. This system identifies and remind  the residential visitors & improve the security convenience of the living environment.</p></div>
  <div class="p-2 bd-highlight"><p class="fs-5">Track our guest's and Trap the stranger's is security based visitor recognition and remainder system.</p></div>
</div>


<div class="use lh-lg">
<div class="row">
  <div class="col-sm-4">
    <div class="card text-center border-0">
     
      <div class="card-body">
        <%= image_tag "web1.svg", height:"120" ,width:"120" %>
        <div class="card-title fs-3">Faster Time to Market</div>
        <div class="card-text fs-6">Achieve compliance with a simple integration that removes all sensitive data from your environment.</div>
      </div>
    </div>
  </div>
  <div class="col-sm-4">
    <div class="card text-center border-0">
     
      <div class="card-body">
        <%= image_tag "web2.svg", height:"120" ,width:"120" %>
        <div class="card-title fs-3">Secure Integrations and Workflows</div>
        <div class="card=text fs-6">Integrate with third-party services, run workflows, and more without storing any sensitive data.</div>
      </div>
    </div>
  </div>
  <div class="col-sm-4">
    <div class="card border-0">
    <div class="card-body text-center">
        <%= image_tag "web3.svg", height:"120" ,width:"120" %>
        <div class="card-title fs-3">Less Complexity</div>
        <div class="card-text fs-6">Replace pricey point solutions with a cost-effective data privacy vault designed for a variety of use cases.</div>
    </div>
    </div>
  </div>
</div>
</div>

<div class="section2 d-flex flex-column bd-highlight text-black bg-gradient">
  <div class="p-2 bd-highlight">
   <div class="row">
    <div class="col-sm-6" >
        <%= image_tag "diagram.svg", height:"629" ,width:"582"%>
    </div>
    <div class="diagram col-sm-6 text-center text-break">
     <p class="fs-1">Track Our Guest's And Trap the Stranger's
     <p class="fs-5">Track our guests and trap the stranger is based on embedded IOT technology
     and a web based application this system is used as residential access control
     management based on visitor recognition and visitors remainder. </p></p>
    </div>
   </div>
  </div>
</div>

<div class="section3 d-flex flex-column bd-highlight text-black bg-gradient">
  <div class="p-2 bd-highlight"><p class="fs-1">Learn More</p></div>
  <div class="p-2 bd-highlight"><p class="fs-5">Avoid the unwanted crime and risks in your residential area . Sign up and Track.</p></div>
</div>

app/views/layouts/_footer.html.erb
<footer class="d-flex flex-wrap justify-content-between align-items-center mt-auto" style="background-color: #163734; border:1px solid black;margin-top:0px;">
 
  <p class="col-md-4 mb-0 text-muted text-white">© 2021 Company,<a class="text-white"<%= link_to 'Visitor Recognition'%></a></p>

    <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
      <%= image_tag "logo.png", height:"55" ,width:"55", :class => "bi me-2"%>
    </a>

    <ul class="nav col-md-4 justify-content-end">
      <li class="nav-item"><%= link_to 'About us', about_us_path, :class =>"text" %></li>
    </ul>

</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <%= image_tag "logo.png", height:"105" ,width:"105" %>
    </a>
    <ul class="nav justify-content-center">
          <li class="nav-item">
             <%= link_to 'About us', about_us_path, :class => 'navbar-link' %>
          </li>
  
          <li class="nav-item">
            <%= link_to 'Blog', edit_user_registration_path, :class => 'navbar-link' %>
           </li>
 
          <li class="nav-item">
            <%= link_to 'Docs', edit_user_registration_path, :class => 'navbar-link' %>
          </li>
    </ul>
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item text-white">
          Logged in as <strong><%= current_user.email %></strong>.
        </li>
        <li class="nav-item">
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        </li>
      <% else %>
        <li class="nav-item">
          <div>
             <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VisitorRecognition</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
  </head>

  <body class="d-flex flex-column min-vh-100">
    <%= render 'layouts/navbar'%>
    <%= yield %>
    <%= render 'layouts/footer'%> 
  </body>
</html>

app/views/visitors/_form.html.erb
<%= form_with(model: visitor) do |form| %>
  <% if visitor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(visitor.errors.count, "error") %> prohibited this visitor from being saved:</h2>

      <ul>
        <% visitor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">

<div class = "row">
  <div class="col-3 edit-visitor">
    <div>
      <%= form.label :name, style: "display: block",:class=>"fw-bold fs-5" %>
      <%= form.text_field :name %>
    </div>
  </div>
  <div class="col-3 edit-visitor">
    <div>
      <%= form.label :relation, style: "display: block" ,:class=>"fw-bold fs-5"%>
      <%= form.text_field :relation %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-3 edit-visitor">
    <div>
      <%= form.label :classification, style: "display: block" ,:class=>"fw-bold fs-5"%>
      <%= form.select :classification, ['guest','stranger'],{prompt:'Select'},{class: "form-control"}%>
    </div>
  </div>
  <div class="col-3 edit-visitor">
    <div>
      <%= form.label :no_of_visit, style: "display: block",:class=>"fw-bold fs-5" %>
      <%= form.number_field :no_of_visit %>
    </div>
  </div>
</div>
<div class="row">
  <div class ="col-3 edit-visitor">
    <div>
      <%= form.label :last_visited, style: "display: block" ,:class=>"fw-bold fs-5"%>
      <%= form.datetime_field :last_visited %>
    </div>
  </div>
  <div class="col-3 edit-visitor">
    <div>
      <%= form.label :notes, style: "display: block" ,:class=>"fw-bold fs-5"%>
      <%= form.text_area :notes %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-3 edit-visitor">
    <div>
      <%= form.submit %>
    </div>
  </div>
  <div class="col-4 edit-visitor">
    <%= link_to "Show this visitor", @visitor,:class=>"btn btn-outline-light"  %> |
    <%= link_to "Back to visitors", visitors_path,:class=>"btn btn-outline-light"  %>
  </div>
</div>
</div>

<% end %>

app/views/visitors/_table.html.erb
<div class="row">
  <h4 class="h4"><%= table_name %></h4>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Gender</th>
        <th scope="col">Visitor Type</th>
        <th scope="col">Visit Count</th>
        <th scope="col">Date and Time</th>
        <th scope="col"> View</th>
      </tr>
    </thead>
    <tbody>
      <% if records.present? %>
        <% records.each_with_index do |record, index|%>
          <tr class="<%= record.classification == 'guest' ? 'table-success' : 'table-danger'%>">
            <td><%= index + 1 %></td>
            <td><%= record&.name %></td>
            <td><%= record&.gender %></td>
            <td><%= record.classification %></td>
            <td><%= record.no_of_visit %></td>
            <td><%= record.last_visited.strftime("%m/%d/%Y %I:%M%p")%></td>
            <td><%= link_to "view", record %></td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td colspan="5" class="table-active text-center">No Data Available</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/visitors/_visitor.html.erb
<div class="container-fluid">
<div id="<%= dom_id visitor %>" class="image_show">
  <div class="row">
    <div class="col-sm-6 fs-4 lh-lg font-monospace">
      <p>
        <strong>Name:</strong>
        <span class="text-light"><%= visitor.name %></span>
      </p>

      <p>
        <strong>Relation:</strong>
        <span class="text-light"><%= visitor.relation %></span>
      </p>

      <p>
        <strong>Classification:</strong>
        <span class="text-light"><%= visitor.classification %></span>
      </p>

      <p>
        <strong>No of visit:</strong>
        <span class="text-light"><%= visitor.no_of_visit %></span>
      </p>

      <p>
        <strong>Last visited:</strong>
        <span class="text-light"><%= visitor.last_visited %></span>
      </p>
    </div>
    <div class="col-sm-6">
      <div class="image_show">
        <p>
          <%= image_tag "data:image/jpeg;base64,#{visitor.image_string}", height: '496', width: '390' %>
        </p>
      </div>
    </div>
  </div>
</div>
<div class="row">
    <div class="col-sm-4 fs-5 font-monospace">
      <p>
        <strong>Notes:</strong>
        <span class="text-light"><%= visitor.notes %></span>
      </p>
   </div>
   <div class="col-sm-3">
   </div>
   <div class="col-sm-4">
      <%= link_to "Edit this visitor", edit_visitor_path(@visitor), :class=>"btn btn-outline-light" %> |
      <%= link_to "Visitors", visitors_path, :class=>"btn btn-outline-light" %>
 
      <%#= button_to "Destroy this visitor", @visitor, method: :delete %>
   </div>
</div>
</div>

app/views/visitors/edit.html.erb
<div class="edit-form lh-lg ">
<h1 class="fs-2 fw-bolder">Editing visitor</h1>

<%= render "form", visitor: @visitor %>
<br>
</div>

app/views/visitors/index.html.erb
<p style="color: green"><%= notice %></p>
<h3 class = "h3"> Dashboard </h3>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-4">
      <div class='card guest'>
        <div class="card-body" style="height: 334px; padding-top: 25%;">
          <h3 class="text-center">GUEST</h3>
          <h4 class="text-center">
            <%=@visitors.count{|visitor| visitor.classification=="guest"}%>    
          </h4>
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class='card stranger'>
        <div class="card-body" style="height: 334px; padding-top: 25%;">
          <h3 class="text-center">STRANGERS</h3>
          <h4 class="text-center"><%=@visitors.count{|visitor| visitor.classification == "stranger"}%></h4>
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="card">
        <div class="card-body">
          <%= pie_chart @visitors.group(:classification).count,donut: true, colors: ["#001a1a","#008A8A"]%>
        </div>
       </div>
    </div>
  </div>
  <br>
  <br>
  <br>
  <div class="row">
    <div class="col-sm-8">
      <%= render 'table', records: @today_visitors, table_name: 'Today Visitors'%>
    </div>
    <div class="col-sm-4">
      <div class="card">
        <div class="card-body">
          <%= column_chart @today_visitors.group(:classification).count,donut: true, colors: ["#001a1a","#008A8A"] %>
        </div>
       </div>
    </div>
  </div>
  <br>
  <br>
  <br>
  <div class="row">
    <div class="col-sm-8">
      <%= render 'table', records: @weekly_visitors, table_name: 'Visitors Within 7 days'%>
    </div>
    <div class="col-sm-4">
      <div class="card">
        <div class="card-body">
          <%= column_chart @weekly_visitors.group(:classification).count,donut: true, colors: ["#001a1a","#008A8A"] %>
        </div>
       </div>
    </div>
  </div>

</div>
<script type="text/javascript">
  function fetchdata(){
    $.ajax({
      url: '/check_visitor',
      type: 'get',
      success: function(response){
        window.location.reload();
      }
    });
  }

  $(document).ready(function(){
    setInterval(fetchdata, 10000);
  });
</script>

app/views/visitors/new.html.erb
<h1>New visitor</h1>

<%= render "form", visitor: @visitor %>

<br>

<div>
  <%= link_to "Back to visitors", visitors_path %>
</div>

app/views/visitors/show.html.erb
<div class="container-fluid" id="show">
  <p style="color: green"><%= notice %></p>
  <%= render @visitor %>
 </div>